
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout/@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t zrwhits/iws-server  .
      - name: Publish Image to docker hub
        run: docker push zrwhits/iws-server:latest

  deploy: 
    needs: build
    runs-on: self-hosted 
    steps: 
      - name: Pull Image from docker hub
        run: docker pull zrwhits/iws-server:latest
      - name: Delete old docker container
        run: docker rm -f iws-server
      - name: Run Docker Container 
        run: docker run -d -p 4000:4000 --name iws-server-container -e MONGO_PASSWORD='${{ secrets.PASSWORD }}' zrwhits/iws-server
